# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
---
apiVersion: v1
kind: Template
metadata:
  name: platform-settings-ui
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: platform-settings-ui
    spec:
      feoConfigEnabled: true
      serviceTiles:
        - id: platform-settings-link
          section: settings
          group: settings
          title: Platform Settings
          href: /settings
          description: Manage notifications, sources, and user preferences
          icon: CogIcon
      searchEntries:
        - id: "platform-settings"
          title: "Platform Settings"
          href: /settings
          description: "Manage notifications, sources, and user preferences"
          alt_title:
            - Platform Settings
            - Settings
            - Notifications
            - Sources
            - User Preferences
      bundleSegments:
        - segmentId: platform-settings
          bundleId: settings
          position: 100
          navItems:
            - id: platform-settings-ui
              title: Platform Settings
              href: /settings
      API:
        versions:
          - v1
      envName: ${ENV_NAME}
      title: Platform Settings
      deploymentRepo: https://github.com/RedHatInsights/platform-settings-ui
      frontend:
        paths:
          - /apps/platform-settings-ui
      image: ${IMAGE}:${IMAGE_TAG}
      pushCacheEnabled: true

      module:
        manifestLocation: '/apps/platform-settings-ui/fed-mods.json'
        modules:
          - id: 'overview'
            module: './RootApp'
            routes:
              - pathname: /settings

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/redhat-services-prod/rh-platform-experien-tenant/platform-settings-ui
