name: Storybook

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: storybook-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  storybook:
    uses: RedHatInsights/experience-ui-governance/.github/workflows/reusable-storybook.yml@5b1eaab981d12bbaad76737b93049f99df04861c # main
    with:
      node-version: 22
